### ISSUE TITLE
Deleting posts is too easy and permanent

### ISSUE THREAD

**Issue by thorva** [chicken-mover/d3mok#16]
Not really sure that there's any reason to let anyone actually delete anything. However, even if this is desired, clicking "delete" in the list of entries should initially just move the post into a deleted category, in which it is in an invisible but retrievable state. 

Since posts are numbered consecutively, this will also create a good record of why there are missing numbers (and prevent numbers from being reassigned when posts are deleted, thus potentially breaking permalinks elsewhere on the internet).

**Comment by petronius** [comment]
Well, all of the IDs right now are subject to revision, because in my utter refusal to allow links to break, the last step of the migration is going to be re-applying the Tumblr post ID numbers to the posts in the new database.

But the point about not re-issuing IDs is a good one -- although MySQL will assign new posts linearly increasing IDs, it does have a tendency to unexpectedly re-use them if it is restarted at some point in the future.

And I like the idea of a "deleted" category, although there will need to be a mechanism for cleaning out cruft (maybe some kind of "actually delete this" option on the deleted posts list).

**Comment by petronius** [comment]
Fixed by 44b6cc1359d66bcf45de30a878cadddb481d9397

Please reopen if you want any changes to the functionality.
